added list aadi

diff --git a/aadisctools/aadisc b/aadisctools/aadisc
--- a/aadisctools/aadisc
+++ b/aadisctools/aadisc
@@ -1,23 +1,36 @@
 #!/usr/bin/env bash
 TOOLS_DIR="/usr/local/bin/aadisctools"
-if [[ $1 == '-c' ]]; then
+case $1 in 
+	'-c')
 	$TOOLS_DIR/checkaadi ${@:2}
 	exit $?
-elif [[ $1 == '-n' ]]; then
+	;;
+	'-n')
 	$TOOLS_DIR/makeaadi ${@:2}
 	exit $?
-elif [[ $1 == '-s' ]]; then
-	$TOOLS_DIR/howaadi ${@:2}
+	;;
+	'-s')
+	$TOOLS_DIR/showaadi ${@:2}
 	exit $?
-elif [[ $1 == '-r' ]]; then
+	;;
+	'-r')
 	$TOOLS_DIR/renameaadi ${@:2}
 	exit $?
-elif [[ $1 == '-R' ]]; then
+	;;
+	'-R')
 	$TOOLS_DIR/removeaadi ${@:2}
 	exit $?
-elif [[ $1 == '--help' ]]; then
+	;;
+	'-l')
+	$TOOLS_DIR/listaadi ${@:2}
+	exit $?
+	;;
+	'--help')
 	echo -e $(cat $TOOLS_DIR/helptext)  
 	exit $?
-fi
-echo -e "Error! WTF WAS THAT\nPlease use \"aadisc --help\" for help"
-exit 1
+	;;
+	*)
+	echo -e "Error! WTF WAS THAT\nPlease use \"aadisc --help\" for help">&2
+	exit 1
+	;;
+esac
diff --git a/aadisctools/checkaadi b/aadisctools/checkaadi
--- a/aadisctools/checkaadi
+++ b/aadisctools/checkaadi
@@ -2,19 +2,18 @@
 ERRRED="\033[1;031m"
 NTXT="\033[0m"
 if [[ $# > 1  ]]; then
-	echo "${ERRRED}Too many arguments $@${NTXT}"
+	echo -e "${ERRRED}Too many arguments $@${NTXT}">&2
 	exit 1
 fi
 
 if [[ $# < 1  ]]; then
-	echo "${ERRRED}Too few arguments $@${NTXT}"
+	echo -e "${ERRRED}Too few arguments $@${NTXT}">&2
 	exit 1
 fi
 
-IFS=$'\n'
 lines=$(grep "alias $1=" $HOME/.aadi_aliases)
 if [[ -z $lines  ]]; then
-	echo -e "${ERRRED}ERROR! ALIAS FOR \"$1\" DOESNT EXIST${NTXT}"
+	echo -e "${ERRRED}ERROR! ALIAS FOR \"$1\" DOESNT EXIST${NTXT}">&2
 	exit 1
 fi
 exit 0
diff --git a/aadisctools/listaadi b/aadisctools/listaadi
--- a/aadisctools/listaadi
+++ b/aadisctools/listaadi
@@ -1,11 +1,16 @@
 #!/usr/bin/env bash
-ERRRED="\033[1;031m"
-NTXT="\033[0m"
+if (( $# != 0 )); then
+	echo -e "\033[1;31mERROR! Too many Arguements!\033[0m" >&2
+	exit 1
+fi
+allaliases=$(grep . "$HOME/.aadi_aliases")
 IFS=$'\n'
-lines=$(grep "alias ="* $HOME/.bash_aliases)
-echo ${lines[0]}
-
-
-
-
+for onealias in $allaliases; do
+	word1=$(cut -d "=" -f 1 <<< $onealias )
+	word2=$(cut -d "=" -f 2 <<< $onealias )
+	echo ${word1:6} ==\>\> ${word2:5:(-2)}
+		
+done
+unset IFS
 exit 0
+
diff --git a/aadisctools/makeaadi b/aadisctools/makeaadi
--- a/aadisctools/makeaadi
+++ b/aadisctools/makeaadi
@@ -3,11 +3,11 @@ ERRRED="\033[1;31m"
 ENDL="\033[0m"
 aliasfile=$HOME/.aadi_aliases
 if [[ $# < 2 ]]; then
-	echo -e "${ERRRED}ERROR! TOO FEW ARGUEMENTS${ENDL}"
+	echo -e "${ERRRED}ERROR! TOO FEW ARGUEMENTS${ENDL}">&2
 	exit 1
 fi
 if [[ $# > 2 ]]; then
-	echo -e "${ERRRED}ERROR! TOO MANY ARGUEMENTS${ENDL}"
+	echo -e "${ERRRED}ERROR! TOO MANY ARGUEMENTS${ENDL}">&2
 	exit 1
 fi
 
@@ -22,11 +22,11 @@ if [[ ${choice^^} == 'N' ]] ; then
 fi
 
 if command -v "$name" >/dev/null 2>&1; then
-	echo -e "${ERRRED}ERROR! $name is a command${ENDL}"
+	echo -e "${ERRRED}ERROR! $name is a command${ENDL}">&2
 	exit 1
 else
 	if grep -q "^alias $name=" $aliasfile $HOME/.bashrc $HOME/.bash_aliases; then
-		echo -e "${ERRRED}ERROR! Alias already exists${ENDL}"
+		echo -e "${ERRRED}ERROR! Alias already exists${ENDL}">&2
 		exit 1
 	fi
 	echo alias $name=\"cd \"$scpath\"\" >> $aliasfile
diff --git a/aadisctools/removeaadi b/aadisctools/removeaadi
--- a/aadisctools/removeaadi
+++ b/aadisctools/removeaadi
@@ -4,10 +4,10 @@ ERRRED="\033[1;31m"
 ENDL="\033[0m"
 
 if [[ $# >1 ]]; then
-	echo -e "${ERRRED}ERROR! TOO MANY ARGUEMENTS${ENDL}"
+	echo -e "${ERRRED}ERROR! TOO MANY ARGUEMENTS${ENDL}">&2
 	exit 1
 elif [[ $# < 1  ]]; then
-	echo -e "${ERRRED}ERROR! TOO FEW ARGUEMENTS${ENDL}" 
+	echo -e "${ERRRED}ERROR! TOO FEW ARGUEMENTS${ENDL}" >&2
 	exit 1
 fi
 
@@ -17,7 +17,6 @@ tempfile=$HOME/.tempaliasaadi
 lines=$(grep "alias"* $aliasfile)
 [[ $? != 0 ]] && exit 1
 
-IFS=$'\n'
 
 /usr/local/bin/aadisctools/checkaadi $1
 [[ $? != 0 ]] && exit 1
@@ -25,15 +24,17 @@ IFS=$'\n'
 touch $tempfile
 [[ $? != 0 ]] && exit 1
 
+IFS=$'\n'
 for line in $lines; do
 	if [[ $line == "alias $1="*  ]]; then
 		# Eat 5 Star do nothing
 		# echo "alias $1=\"cd \"$newpath\"\"">>$tempfile
+		true
 	else	
 		echo $line >> $tempfile	
 	fi
 done
-
+unset IFS
 cat $tempfile>$aliasfile
 [[ $? != 0 ]] && exit 1
 
diff --git a/aadisctools/renameaadi b/aadisctools/renameaadi
--- a/aadisctools/renameaadi
+++ b/aadisctools/renameaadi
@@ -3,10 +3,10 @@ ERRRED="\033[1;31m"
 ENDL="\033[0m"
 
 if [[ $# >1 ]]; then
-	echo -e "${ERRRED}ERROR! TOO MANY ARGUEMENTS${ENDL}"
+	echo -e "${ERRRED}ERROR! TOO MANY ARGUEMENTS${ENDL}" >&2
 	exit 1
 elif [[ $# < 1  ]]; then
-	echo -e "${ERRRED}ERROR! TOO FEW ARGUEMENTS${ENDL}" 
+	echo -e "${ERRRED}ERROR! TOO FEW ARGUEMENTS${ENDL}" >&2
 	exit 1
 fi
 
@@ -15,8 +15,8 @@ tempfile=$HOME/.tempaliasaadi
 
 
 lines=$(grep "alias"* $aliasfile)
-IFS=$'\n'
 /usr/local/bin/aadisctools/checkaadi $1
+
 [[ $? != 0 ]] && exit 1
 
 read -p "Where do you want \"$1\" to lead? " newpath
@@ -24,12 +24,14 @@ read -p "Where do you want \"$1\" to lead? " newpath
 
 if [ -e "$newpath" ]; then
 else
-	echo -e "${ERRRED}ERROR! Path does not exist${ENDL}"
+	echo -e "${ERRRED}ERROR! Path does not exist${ENDL}">&2
 	exit 1
 fi
 
 touch $tempfile
 [[ $? != 0 ]] && exit 1
+
+IFS=$'\n'
 
 for line in $lines; do
 	if [[ $line == "alias $1="*  ]]; then
@@ -38,7 +40,7 @@ for line in $lines; do
 		echo $line >> $tempfile	
 	fi
 done
-
+unset IFS
 cat $tempfile>$aliasfile
 [[ $? != 0 ]] && exit 1
 
