Minor bug fixes

diff --git a/aadisctools/renameaadi b/aadisctools/renameaadi
--- a/aadisctools/renameaadi
+++ b/aadisctools/renameaadi
@@ -23,9 +23,7 @@ read -p "Where do you want \"$1\" to lead? " newpath
 [[ $? != 0 ]] && exit 1
 
 if [ -e "$newpath" ]; then
-	true
-else
-	echo -e "${ERRRED}ERROR! Path does not exist${ENDL}">&2
+	echo -e "${ERRRED}ERROR! Path $newpath does not exist${ENDL}">&2
 	exit 1
 fi
 
